# Site settings
title: Jonathan Serrano
description: > # this means to ignore newlines until "baseurl:"
    I'm a backend software developer specializing in Ruby. I am always eager to learn new languages, frameworks and tools. I am community oriented, enjoy sports and traveling.
url: "github.io/jonathansr"
baseurl: ""
logo: Jonathan-<b>Serrano</b>
paginate: 5
paginate_path: "/blog/page:num/"
owner:
    email: Jonathan.Serranor@gmail.com
    github:
        show: true
        username: "JonathanSR"
    twitter:
        show: false
        username: ""
    linkedin:
        show: true
        profile: "https://linkedin.com/in/jserranor"
sass:
    sass_dir: _sass
    style: compressed
permalink: "/article/:title"
markdown: kramdown
highlighter: pygments
gems:
    - jekyll-feed
    - jekyll-paginate
collections:
    projects:
        output: true
